const envConfig = require('nconf');

const NODE_ENV = envConfig.get("NODE_ENV") || 'development';

module.exports = {
  get ROUTING_CODE_TYPE(){ 
    return [
    'SWIFT',
    'IFSC',
    'SORT CODE',
    'ACH CODE',
    'BRANCH CODE',
    'BSB CODE',
    'BANK CODE',
    'LOCATION ID',
  ]
},
  get COUNTRIES (){
   return [
      'IN',
      'AU',
      'BE',
      'SG',
      'HK',
      'US',
      'MY',
      'CN',
      'JP',
      'BD',
      'DE',
      'PH',
      'TH',
      'GB',
      'ID',
      'LK',
      'TW',
      // 'EU',
      'MO',
      'VN',
      'NP',
      'NZ',
      'BH',
      'BG',
      'CA',
      'HR',
      'CZ',
      'DK',
      'AE',
      'HU',
      'IL',
      'KW',
      'MX',
      'NO',
      'OM',
      'PL',
      'QA',
      'RO',
      'SA',
      'ZA',
      'SE',
      'CH',
      'IE',
      'FI',
      'KR',
      'SK',
      'PG',
      'KH',
      'AT',
      'CY',
      'FR',
      'GR',
      'IT',
      'LA',
      'LI',
      'LT',
      'LU',
      'MT',
      'NL',
      'PK',
      'PT',
      'PR',
      'SC',
      'SI',
      'ES',
    ]
  },
  get TRULIOO_URL() {
    if (NODE_ENV === 'production') {
      return '';
    }
    return '';
  },
  get MARGIN() {
    return 0.50;
  },
  get FRONT_END_HOST() {
    if (NODE_ENV === 'development') {
      return 'http://localhost:4701';
    } else if (NODE_ENV === 'test') {
      return 'http://161.202.19.190:4701';
    } else if (NODE_ENV === 'production') {
      return '';
    }
  },
  get PASSWORD_REGEX() {
    if (NODE_ENV === 'production') {
      return /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~]{8,32}$/;
    } else {
      return /[\s\S]*/;
    }
  },
  get CURRENCY_PAIR() {
    return {
      EURHKD: 'EURHKD=X',
      EURMYR: 'EURMYR=X',
      EURINR: 'EURINR=X',
      EURTHB: 'EURTHB=X',
      EURSGD: 'EURSGD=X',
      EURGBP: 'EURGBP=X',
      EURPHP: 'EURPHP=R',
      EURLKR: 'EURLKR=R',
      EURUSD: 'EUR=X',
      EURCNY: 'EURCNY=X',
      USDGBP: 'USDGBP=R',
      USDEUR: 'USDEUR=R',
      USDSGD: 'SGD=X',
      USDTHB: 'THB=X',
      USDINR: 'INR=X',
      USDMYR: 'MYR=X',
      USDPHP: 'PHP=X',
      USDLKR: 'LKR=X',
      USDUSD: 'USD=X',
      USDMOP: 'MOP=X',
      USDTWD: 'TWD=X',
      USDHKD: 'HKD=X',
      USDCNY: 'CNY=X',
      USDJPY: 'JPY=X',
      USDIDR: 'IDR=X',
      USDVND: 'VND=X',
      TWDHKD: 'TWDHKD=X',
      TWDMYR: 'TWDMYR=R',
      TWDJPY: 'TWDJPY=X',
      TWDTHB: 'TWDTHB=R',
      TWDIDR: 'TWDIDR=R',
      TWDSGD: 'TWDSGD=X',
      TWDGBP: 'TWDGBP=X',
      TWDINR: 'TWDINR=R',
      TWDCNY: 'TWDCNY=R',
      TWDPHP: 'TWDPHP=R',
      TWDUSD: 'TWDUSD=R',
      TWDLKR: 'TWDLKR=R',
      HKDMOP: 'HKDMOP=R',
      HKDMYR: 'HKDMYR=R',
      HKDJPY: 'HKDJPY=R',
      HKDTHB: 'HKDTHB=R',
      HKDIDR: 'HKDIDR=R',
      HKDVND: 'HKDVND=R',
      HKDSGD: 'HKDSGD=R',
      HKDGBP: 'HKDGBP=R',
      HKDINR: 'HKDINR=R',
      HKDCNY: 'HKDCNY=R',
      HKDPHP: 'HKDPHP=R',
      HKDUSD: 'HKDUSD=R',
      HKDLKR: 'HKDLKR=R',
      HKDTWD: 'HKDTWD=R',
      JPYHKD: 'JPYHKD=R',
      JPYMOP: 'JPYMOP=R',
      JPYMYR: 'JPYMYR=R',
      JPYTHB: 'JPYTHB=R',
      JPYIDR: 'JPYIDR=R',
      JPYVND: 'JPYVND=R',
      JPYSGD: 'JPYSGD=R',
      JPYGBP: 'JPYGBP=R',
      JPYINR: 'JPYINR=R',
      JPYCNY: 'JPYCNY=R',
      JPYPHP: 'JPYPHP=R',
      JPYUSD: 'JPYUSD=R',
      JPYLKR: 'JPYLKR=R',
      JPYTWD: 'JPYTWD=R',
      THBHKD: 'THBHKD=R',
      THBMYR: 'THBMYR=R',
      THBJPY: 'THBJPY=R',
      THBIDR: 'THBIDR=R',
      THBVND: 'THBVND=R',
      THBSGD: 'THBSGD=R',
      THBGBP: 'THBGBP=R',
      THBINR: 'THBINR=R',
      THBCNY: 'THBCNY=R',
      THBPHP: 'THBPHP=R',
      THBUSD: 'THBUSD=R',
      THBLKR: 'THBLKR=R',
      THBTWD: 'THBTWD=R',
      IDRHKD: 'IDRHKD=R',
      IDRMOP: 'IDRMOP=R',
      IDRMYR: 'IDRMYR=R',
      IDRJPY: 'IDRJPY=R',
      IDRTHB: 'IDRTHB=R',
      IDRVND: 'IDRVND=R',
      IDRSGD: 'IDRSGD=R',
      IDRGBP: 'IDRGBP=R',
      IDRINR: 'IDRINR=R',
      IDRCNY: 'IDRCNY=R',
      IDRPHP: 'IDRPHP=R',
      IDRUSD: 'IDRUSD=R',
      IDRLKR: 'IDRLKR=R',
      MYRHKD: 'MYRHKD=R',
      MYRMOP: 'MYRMOP=R',
      MYRJPY: 'MYRJPY=R',
      MYRTHB: 'MYRTHB=R',
      MYRIDR: 'MYRIDR=R',
      MYRVND: 'MYRVND=R',
      MYRSGD: 'MYRSGD=R',
      MYRGBP: 'MYRGBP=R',
      MYRINR: 'MYRINR=R',
      MYRCNY: 'MYRCNY=R',
      MYRPHP: 'MYRPHP=R',
      MYRUSD: 'MYRUSD=R',
      MYRLKR: 'MYRLKR=R',
      MYRTWD: 'MYRTWD=R',
      VNDHKD: 'VNDHKD=R',
      VNDMYR: 'VNDMYR=R',
      VNDJPY: 'VNDJPY=R',
      VNDTHB: 'VNDTHB=R',
      VNDIDR: 'VNDIDR=R',
      VNDSGD: 'VNDSGD=R',
      VNDGBP: 'VNDGBP=R',
      VNDINR: 'VNDINR=R',
      VNDCNY: 'VNDCNY=R',
      VNDPHP: 'VNDPHP=R',
      VNDUSD: 'VNDUSD=R',
      VNDLKR: 'VNDLKR=R',
      VNDTWD: 'VNDTWD=R',
      INRVND: 'INRVND=R',
      INRMOP: 'INRMOP=R',
      INRMYR: 'INRMYR=R',
      INRJPY: 'INRJPY=R',
      INRTHB: 'INRTHB=R',
      INRIDR: 'INRIDR=R',
      INRSGD: 'INRSGD=R',
      INRGBP: 'INRGBP=R',
      INRCNY: 'INRCNY=R',
      INRPHP: 'INRPHP=R',
      INRUSD: 'INRUSD=R',
      INRLKR: 'INRLKR=R',
      INRTWD: 'INRTWD=R',
      CNYHKD: 'CNYHKD=R',
      CNYMOP: 'CNYMOP=R',
      CNYMYR: 'CNYMYR=R',
      CNYJPY: 'CNYJPY=R',
      CNYTHB: 'CNYTHB=R',
      CNYIDR: 'CNYIDR=R',
      CNYSGD: 'CNYSGD=R',
      CNYGBP: 'CNYGBP=R',
      CNYINR: 'CNYINR=X',
      CNYPHP: 'CNYPHP=R',
      CNYUSD: 'CNYUSD=X',
      CNYLKR: 'CNYLKR=R',
      CNYTWD: 'CNYTWD=R',
      PHPHKD: 'PHPHKD=R',
      PHPMYR: 'PHPMYR=R',
      PHPJPY: 'PHPJPY=R',
      PHPTHB: 'PHPTHB=R',
      PHPIDR: 'PHPIDR=R',
      PHPVND: 'PHPVND=R',
      PHPSGD: 'PHPSGD=R',
      PHPGBP: 'PHPGBP=R',
      PHPINR: 'PHPINR=R',
      PHPCNY: 'PHPCNY=R',
      PHPUSD: 'PHPUSD=R',
      PHPLKR: 'PHPLKR=R',
      SGDHKD: 'SGDHKD=R',
      SGDMYR: 'SGDMYR=R',
      SGDJPY: 'SGDJPY=R',
      SGDTHB: 'SGDTHB=R',
      SGDIDR: 'SGDIDR=R',
      SGDVND: 'SGDVND=R',
      SGDGBP: 'SGDGBP=R',
      SGDINR: 'SGDINR=R',
      SGDCNY: 'SGDCNY=R',
      SGDPHP: 'SGDPHP=R',
      SGDUSD: 'SGDUSD=R',
      SGDLKR: 'SGDLKR=R',
      SGDTWD: 'SGDTWD=R',
      GBPHKD: 'GBPHKD=R',
      GBPMOP: 'GBPMOP=R',
      GBPMYR: 'GBPMYR=R',
      GBPJPY: 'GBPJPY=R',
      GBPTHB: 'GBPTHB=R',
      GBPIDR: 'GBPIDR=R',
      GBPVND: 'GBPVND=R',
      GBPSGD: 'GBPSGD=R',
      GBPINR: 'GBPINR=R',
      GBPCNY: 'GBPCNY=R',
      GBPPHP: 'GBPPHP=R',
      GBPLKR: 'GBPLKR=R',
      GBPTWD: 'GBPTWD=R',
      MOPHKD: 'MOPHKD=R',
      MOPMYR: 'MOPMYR=R',
      MOPTHB: 'MOPTHB=R',
      MOPIDR: 'MOPIDR=R',
      MOPSGD: 'MOPSGD=R',
      MOPGBP: 'MOPGBP=R',
      MOPINR: 'MOPINR=R',
      MOPCNY: 'MOPCNY=R',
      MOPPHP: 'MOPPHP=R',
      MOPUSD: 'MOPUSD=R',
      MOPTWD: 'MOPTWD=R',
      MOPJPY: 'MOPJPY=R',
      LKRMYR: 'LKRMYR=R',
      LKRJPY: 'LKRJPY=R',
      LKRIDR: 'LKRIDR=R',
      LKRVND: 'LKRVND=R',
      LKRSGD: 'LKRSGD=R',
      LKRGBP: 'LKRGBP=R',
      LKRINR: 'LKRINR=R',
      LKRCNY: 'LKRCNY=R',
      LKRPHP: 'LKRPHP=R',
      LKRUSD: 'LKRUSD=R',
      LKRTWD: 'LKRTWD=R',
    };
  },
  get TABLE_NAME(){
    return {
      payees:'payees'
    }
  }
};